const data = [
  {
    id: 1,
    name: "Palm Harbor",
    img: "building1.jpg",
    Price: 2095,
    address: "2699 Green Valley, Highland Lake, FL",
    beds: 3,
    bathrooms: 2,
    area: "5x7",
  },
  {
    id: 2,
    name: "Beverly Springfield",
    img: "building2.jpg",
    Price: 2700,
    address: "2821 Lake Sevilla, Palm Harbor, TX",
    beds: 4,
    bathrooms: 2,
    area: "6x7.5",
  },
  {
    id: 3,
    name: "Faulkner Ave",
    img: "building3.jpg",
    Price: 4550,
    address: "909 Woodland St. Michigan, IN",
    beds: 4,
    bathrooms: 3,
    area: "8x10",
  },
  {
    id: 4,
    name: "Palm Harbor II",
    img: "building1.jpg",
    Price: 2295,
    address: "2699 Green Valley, Highland Lake, FL",
    beds: 3,
    bathrooms: 2,
    area: "5x7",
  },
  {
    id: 5,
    name: "Beverly Springfield II",
    img: "building2.jpg",
    Price: 2900,
    address: "2821 Lake Sevilla, Palm Harbor, TX",
    beds: 4,
    bathrooms: 2,
    area: "6x7.5",
  },
  {
    id: 6,
    name: "Faulkner Ave II",
    img: "building3.jpg",
    Price: 3550,
    address: "909 Woodland St. Michigan, IN",
    beds: 4,
    bathrooms: 3,
    area: "8x10",
  },
];
export default data;
